### ISSUE TITLE
Route Animations

### ISSUE THREAD

**Issue by elliotjberman** [elliotjberman/website#2]
- [ ] Animate name-card entrance
- [ ] Manage grayscale animations across the site
- [ ] Deal with loading website from different routes for all navigation

**Comment by vaprdev** [comment]
0/3 after more than 6 months? And you call yourself a dev...

**Comment by elliotjberman** [comment]
Should be closed sorry!


Elliot

**Comment by vaprdev** [comment]
It's still open...

**Comment by vaprdev** [comment]
Good
